sol
mate-academy/py-asyncio-iot pull request #392
Opened 2024-08-21 12:17 UTC by NikitaNikolaitsev

2024-08-22 10:25 UTC, Arsen-hrynevych requested changes
Thanks

2024-08-22 10:25 UTC, Arsen-hrynevych commented on app/iot/service.py
> +            await self.send_msg(msg)
You should use gather here

2024-08-22 10:25 UTC, Arsen-hrynevych commented on app/main.py
> +from typing import Any, Awaitable
Imports should be grouped and separated by a blank line according to standard library, external libraries, and custom imports. This practice enhances both code readability and maintainability. 
Read more about topic [here](https://peps.python.org/pep-0008/#imports)

2024-08-22 13:38 UTC, maxgerman requested changes
the order of execution needs fixing

2024-08-22 13:38 UTC, maxgerman commented on app/main.py
> +    await run_parallel(*wake_up_program)
you're trying to run "turn on" and "play" concurrently - we need to guarantee the correct order here

2024-08-22 15:48 UTC, maxgerman requested changes
see comments

2024-08-22 15:48 UTC, maxgerman commented on app/main.py
>          service.send_msg(Message(hue_light_id, MessageType.SWITCH_ON)),
this way we wait for the light before anything else - this can be done at the same time as switching on the speaker

2024-08-22 15:48 UTC, maxgerman commented on app/main.py
> +    wake_up_program.append(
why appending instead of just adding to the list literal?

2024-09-04 19:51 UTC, maxgerman requested changes
one program still isn't fixed

2024-09-04 19:51 UTC, maxgerman commented on app/main.py
>          service.send_msg(Message(hue_light_id, MessageType.SWITCH_ON)),
this is still true

2024-09-08 12:18 UTC, maxgerman approved these changes

2024-09-08 12:18 UTC, maxgerman commented on app/main.py
> +        run_parallel(
yes, but you don't have to nest multiple `run_parallel` here

2024-09-30 11:12 UTC, closed without merging